#!/bin/bash

# Quick Command Reference for GamerX Development

echo "=========================================="
echo "GamerX - Quick Commands Reference"
echo "=========================================="
echo ""
echo "🚀 START DEVELOPMENT"
echo "==================="
echo "# Terminal 1 - Backend"
echo "cd backend && npm run dev"
echo ""
echo "# Terminal 2 - Frontend"
echo "cd frontend && npm start"
echo ""
echo ""
echo "📊 DATABASE COMMANDS"
echo "===================="
echo "# Connect to database"
echo "psql -U gamerx_user -d gamerx"
echo ""
echo "# View all users"
echo "SELECT id, username, email, created_at FROM users;"
echo ""
echo "# Reset password (in psql)"
echo "ALTER USER gamerx_user WITH PASSWORD 'new_password';"
echo ""
echo "# Backup database"
echo "pg_dump -U gamerx_user gamerx > backup.sql"
echo ""
echo "# Restore database"
echo "psql -U gamerx_user gamerx < backup.sql"
echo ""
echo ""
echo "📦 NPM COMMANDS"
echo "==============="
echo "# Install dependencies"
echo "cd backend && npm install"
echo "cd frontend && npm install"
echo ""
echo "# Production build (frontend)"
echo "cd frontend && npm run build"
echo ""
echo ""
echo "🔧 ENVIRONMENT"
echo "=============="
echo "# Create .env file"
echo "cp backend/.env.example backend/.env"
echo ""
echo "# Generate secure JWT secret"
echo "node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""
echo ""
echo "🧪 API TESTING"
echo "=============="
echo "# Test API health"
echo "curl http://localhost:5000/health"
echo ""
echo "# Register user"
echo "curl -X POST http://localhost:5000/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"username\":\"test\",\"email\":\"test@example.com\",\"password\":\"password123\"}'"
echo ""
echo "# Login"
echo "curl -X POST http://localhost:5000/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"password123\"}'"
echo ""
echo ""
echo "📝 DOCUMENTATION"
echo "================"
echo "# View setup guide"
echo "cat SETUP_GUIDE.md"
echo ""
echo "# View database guide"
echo "cat DATABASE_GUIDE.md"
echo ""
echo "# View main README"
echo "cat README.md"
echo ""
